<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:t="http://www.tei-c.org/ns/1.0" xmlns:my="http://lb42.github.io"
    xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.w3.org/1999/xhtml" version="2.0">
    <xsl:output method="html" exclude-result-prefixes="#all" encoding="utf-8" indent="yes"/>
    <xsl:variable name="now" select="current-time()"/>
    <xsl:variable name="today" select="current-date()"/>
    <xsl:param name="nLangs" select="15" as="xs:integer"/>
    <xsl:param name="iterations" select="42" as="xs:integer"/>
    <xsl:param name="verbose"/>
<xsl:variable name="limit" >
    <xsl:value-of select="$iterations*$nLangs"/></xsl:variable>
    <!-- first generate $limit numbers in the range 1 : $nLangs -->
    <xsl:variable name="randomLangs"
        select="tokenize(unparsed-text(
        'https://www.random.org/integers/?num=630&amp;min=1&amp;max=15&amp;col=5&amp;base=10&amp;format=plain&amp;rnd=new'),'\s')"/>

    <xsl:template match="t:teiHeader/t:fileDesc/t:editionStmt/t:edition/t:date">
        <date>
            <xsl:value-of select="$today"/>
        </date>
    </xsl:template>
    <xsl:template match="/">
        <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
            <head>
                <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
                <!--THIS FILE IS GENERATED FROM AN XML MASTER. DO NOT EDIT (5)-->
                <title>Poema sans grenzen </title>
                <meta name="author" content="Rip Bulkeley"/>
                <meta name="generator" content="Generated by an XSLT stylesheets"/>
                <meta name="DC.Title" content="Poema sans grenzen"/>
                <meta name="DC.Type" content="Text"/>
                <meta name="DC.Format" content="text/html"/>
                <link rel="stylesheet" type="text/css" media="screen, projection"
                    href="http://www.w3.org/Talks/Tools/Slidy/show.css"/>
                <link href="rip.css" rel="stylesheet" type="text/css"/>
                <script src="http://www.w3.org/Talks/Tools/Slidy/slidy.js" type="text/javascript"/>

            </head>
            <body class="simple" id="TOP">

                <xsl:variable name="offsets" as="xs:integer *">
                    <xsl:for-each select="0 to $iterations">
                        <xsl:value-of select=". * 5"/>
                    </xsl:for-each>
                </xsl:variable>

                <xsl:variable name="message">
                    <xsl:text>The time is </xsl:text>
                    <xsl:value-of select="$now"/>
                    <xsl:text>We have </xsl:text>
                    <xsl:value-of select="$limit"/>
                    <xsl:text> random numbers </xsl:text>
                    <xsl:value-of select="$randomLangs"/>
                    <xsl:text>
               </xsl:text>
                    <xsl:text>Offsets are </xsl:text>
                    <xsl:value-of select="$offsets"/>
                    <xsl:text>
               </xsl:text>
                </xsl:variable>
                <xsl:if test="$verbose">
                    <xsl:comment><xsl:value-of select="$message"/></xsl:comment>
                </xsl:if>
                <xsl:variable name="ROOT" select="."/>
                <xsl:for-each select="$offsets">
                    <xsl:variable name="offset" select="."/>
                    <xsl:if test="$verbose">
                        <xsl:comment>Choosing language <xsl:value-of select="$limit"/> - <xsl:value-of select="$offset"/> </xsl:comment>
                    </xsl:if>
                    <xsl:variable name="rHead" select="$randomLangs[$limit - $offset]"/>
                    <div class="slide">
                        <xsl:if test="$verbose">
                            <xsl:comment> Offset is <xsl:value-of select="$offset"/> Head lang is <xsl:value-of select="$rHead"/></xsl:comment>
                        </xsl:if>

                        <xsl:apply-templates
                            select="$ROOT//t:lg[string(position()) = $rHead]/t:head[1]"/>

                        <xsl:for-each select="1 to 5">
                            <xsl:variable name="line" select="."/>
                            <xsl:variable name="rLang" select="$randomLangs[$line + $offset]"/>
                            <xsl:if test="$verbose">
                                <xsl:comment>Stanza <xsl:value-of select="$rLang"/> line <xsl:value-of select="$line"/></xsl:comment>
                            </xsl:if>
                            <xsl:apply-templates
                                select="
                                    $ROOT//t:body/t:lg[string(position()) =
                                    $rLang]/t:l[position() = $line]"
                            />
                        </xsl:for-each>
                    </div>

                </xsl:for-each>
            </body>
        </html>
    </xsl:template>
   
    <xsl:template match="t:l">
        <xsl:variable name="ln">
            <xsl:value-of select="concat('l', @n)"/>
        </xsl:variable>
        <div class="{$ln}">
            <xsl:attribute name="xml:lang">
                <xsl:value-of select="parent::t:lg/@xml:lang"/>
            </xsl:attribute>
            <xsl:apply-templates/>
        </div>
    </xsl:template>

    <xsl:template match="t:head">
        <div class="title">
            <xsl:attribute name="xml:lang">
                <xsl:value-of select="parent::t:lg/@xml:lang"/>
            </xsl:attribute>
            <xsl:apply-templates/>
        </div>
    </xsl:template>

       <xsl:template match="node() | @*">
        <xsl:copy>
            <xsl:apply-templates select="node() | @*"/>
        </xsl:copy>
    </xsl:template>
</xsl:stylesheet>
